### ISSUE TITLE
Открытие ветки в git.sbis.ru по ее названию

### ISSUE THREAD

**Issue by gopkill** [saby-customizer/saby-customizer.github.io#4]
Для сгенерированного и сохраненного названия ветки было бы не плохо иметь возможность перейти прямо в репозиторий в нужный бранч по ссылке.

**Comment by IgorNovozhilov** [comment]
@IgorNovozhilov один из вариантов решения: https://online.sbis.ru/open_dialog.html?guid=af247760-fa92-4ed9-97e2-f682d2ebefd5&user=d7dde799-21cb-49ea-89cf-de56e4f7f78b

**Comment by IgorNovozhilov** [comment]
Добавил кнопку для регламента MR, откроет все ветки из MR в RC ветку вехи MR
