### ISSUE TITLE
Версия вехи берется та, которая была при создании

### ISSUE THREAD

**Issue by gutrety76** [saby-customizer/saby-customizer.github.io#8]
Версия вехи берется та, которая была при создании. Тоесть создают ошибку с версией 23.0000  и она не обновляется. Хотелось бы чтобы плагин забирал актуальную версию. наверное проблема в коде на картинке в файле git-branch.js
![image](https://github.com/saby-customizer/saby-customizer.github.io/assets/125618426/dadd8afb-75db-41e3-9dc0-e65fb724f98b)

**Comment by IgorNovozhilov** [comment]
Больше не будет сохранять в историю данные от задач без вехи, и такой проблемы не будет
